### ISSUE TITLE
Build a native image

### ISSUE THREAD

**Issue by kaklakariada** [exasol/bucketfs-client#10]
BFSC is currently delivered as an executable JAR that requires installing a JVM for running. We should build and deliver a native executable for macOS, Linux and Windows so that users don't need to install a JVM for running BFSC.

## Acceptance Criteria
1. An executable for macOS, Linux and Windows is uploaded to the release page (in addition to the jar)
2. Integration tests verify that the executable works on all three platforms
3. User guide describes how to use the executable

See https://github.com/exasol/parquet-edml-generator/pull/20 for an example

**Comment by ckunki** [comment]
See 
* create sha256 checksum on MacOS https://unix.stackexchange.com/questions/426837/no-sha256sum-in-macos
* create sha256 checksum on Windows with Powershell https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash?view=powershell-7.3
* Powershell file encoding: remove UTF-8 BOM from file: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_character_encoding?view=powershell-7.3
* https://stackoverflow.com/questions/2035193/how-to-run-a-powershell-script
