### ISSUE TITLE
Remove class ListingProvider 

### ISSUE THREAD

**Issue by ckunki** [exasol/bucketfs-client#19]
After https://github.com/exasol/bucketfs-java/issues/57 is implemented  class `ListingProvider` can be removed

## Dependencies

- [x] https://github.com/exasol/bucketfs-java/issues/57

**Comment by kaklakariada** [comment]
Unblocked, https://github.com/exasol/bucketfs-java/issues/57 is implemented in `bucketfs-java` 3.1.0
