### ISSUE TITLE
Execution on macOS 

### ISSUE THREAD

**Issue by ckunki** [exasol/bucketfs-client#26]
I was not able to run the application from the terminal on macOS Monterey, 
maybe this option also needs to be explained better. 

Signing for macOS binaries will not be possible in near future.

Until then the macOS binaries should be removed 
* from releases 
* and documentation

**Comment by kaklakariada** [comment]
Execution on MacOS 13.2.1 first fails because the executable flag is not set. After setting it with `chmod u+x bfsc-mac_x86` execution fails with this error dialog:

![image](https://user-images.githubusercontent.com/4711730/224947512-b33fe47b-b694-4312-b5fe-a7bedc9dfde1.png)

**Comment by exatn** [comment]
Yeah I had the exact same result although I used chmod a+x or 755.
